name: Add RLS
description: "Want to make Bloxs suffer? You've come to the right place!"
labels: ["rls"]
assignees: [Blocksnmore]

body:
  - type: input
    attributes:
      label: "What table needs RLS"
      description: "What would need to be RLS'd"
      placeholder: "Users"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "What RLS is needed"
      description: "Describe what's needed in the RLS policy"
      placeholder: "Allow users to ban anyone they want"
    validations:
      required: true
