import "./globals.css";
import type { ReactNode } from "react";
import { useState } from "react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import Supabase from "../components/Supabase";

interface RootProps {
	children: ReactNode;
}

export default function RootLayout(props: RootProps) {
	return (
		<html lang="en">
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<Supabase>
					<div className="flex flex-col min-h-screen">
						<div className="flex-1">
							<Navbar />
							{props.children}
						</div>
						<Footer />
					</div>
				</Supabase>
			</body>
		</html>
	);
}
