name: Deno Lint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Lint
        run: deno lint --config=deno.jsonc
